name: 'AVM Action'
description: 'A Python-based GitHub Action for working with Terraform in Azure Verified Modules (AVM)-style environments'
author: 'Action-Foundry'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  tf_directory:
    description: 'Path to the Terraform configuration directory'
    required: false
    default: '.'
  tfvars_files:
    description: 'Comma-separated list of tfvars files or glob pattern'
    required: false
    default: ''
  backend_config_file:
    description: 'Path to the backend configuration file'
    required: false
    default: ''
  command:
    description: 'Terraform command to run (init, plan, apply, destroy, validate)'
    required: true
    default: 'plan'
  workspace:
    description: 'Terraform workspace to use'
    required: false
    default: 'default'
  azure_subscription_id:
    description: 'Azure Subscription ID'
    required: false
    default: ''
  azure_tenant_id:
    description: 'Azure Tenant ID'
    required: false
    default: ''
  azure_client_id:
    description: 'Azure Client ID (optional; prefer OIDC)'
    required: false
    default: ''
  var_overrides:
    description: 'JSON or key=value pairs for variable overrides'
    required: false
    default: ''
  log_level:
    description: 'Logging level (DEBUG, INFO, WARNING, ERROR)'
    required: false
    default: 'INFO'
  avm_version:
    description: 'Azure Verified Modules version to use (e.g., "0.1.0" or "latest")'
    required: false
    default: 'latest'
  terraform_version:
    description: 'Terraform version to use (e.g., "1.6.0" or "latest")'
    required: false
    default: 'latest'
  azurerm_version:
    description: 'Azure RM provider version to use (e.g., "3.85.0" or "latest")'
    required: false
    default: 'latest'

outputs:
  plan_output:
    description: 'Output from terraform plan command'
  state_summary:
    description: 'Summary of the Terraform state changes'

runs:
  using: 'docker'
  image: 'Dockerfile'
